version: '3.8'

services:
  hibernate-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9092:9092"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/hibernate
      - SPRING_DATASOURCE_USERNAME=hibernate-user
      - SPRING_DATASOURCE_PASSWORD=Dharan@123
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0.30
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Dharan@123
      MYSQL_DATABASE: hibernate
      MYSQL_USER: hibernate-user
      MYSQL_PASSWORD: Dharan@123
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      retries: 5
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: {}
