version: '3'
services:
  hibernate-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9092:9092"  # Exposing Tomcat port 9092
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://192.168.56.25:3306/hibernate
      - SPRING_DATASOURCE_USERNAME=hibernate-user
      - SPRING_DATASOURCE_PASSWORD=Dharan@123
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0.30
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Dharan@123
      MYSQL_DATABASE: hibernate
      MYSQL_USER: hibernate-user
      MYSQL_PASSWORD: Dharan@123
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      retries: 5
