CREATE DATABASE IF NOT EXISTS hibernate;
USE hibernate;
CREATE TABLE IF NOT EXISTS Users (
    user_id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL
);
CREATE USER IF NOT EXISTS 'hibernate-user'@'%' IDENTIFIED BY 'Dharan@123';
GRANT ALL PRIVILEGES ON hibernate.* TO 'hibernate-user'@'%';
FLUSH PRIVILEGES;